name: Trigger Reusable Workflow 

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Registry Release Version'
        required: true
      snapshot-version:
        description: 'Next snapshot version'
        required: true

jobs: 
    job1:
      name: first job
      runs-on: ubuntu-latest
      steps: 
        - name: step1
          uses: actions/checkout@v2
        - name: step2
          run: env | short
    job2: 
      name: secound job
      runs-on: windows-latest
      steps:
        - name: step1
          uses: actions/checkout@v2
        - name: step2
          run: "Get-ChildItem Env: | Sort-Object Name"
          
    job3:
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        release-version: ${{ github.event.inputs.release-version}}
        snapshot-version: ${{ github.event.inputs.snapshot-version}}
    
